// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: gss.proto

package gsspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_UNKNOWN   QueryType = 0
	QueryType_MINECRAFT QueryType = 1
	QueryType_GAMEQ     QueryType = 2
	QueryType_GAMEDIG   QueryType = 3
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MINECRAFT",
		2: "GAMEQ",
		3: "GAMEDIG",
	}
	QueryType_value = map[string]int32{
		"UNKNOWN":   0,
		"MINECRAFT": 1,
		"GAMEQ":     2,
		"GAMEDIG":   3,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_gss_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_gss_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_gss_proto_rawDescGZIP(), []int{0}
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host" xml:"host"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port" xml:"port"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" xml:"name"`
	MapName       string                 `protobuf:"bytes,4,opt,name=map_name,json=mapName,proto3" json:"map_name" xml:"map_name"`
	MaxPlayers    int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players" xml:"max_players"`
	NumPlayers    int32                  `protobuf:"varint,6,opt,name=num_players,json=numPlayers,proto3" json:"num_players" xml:"num_players"`
	Players       []*Player              `protobuf:"bytes,7,rep,name=players,proto3" json:"players" xml:"players"`
	QueryType     QueryType              `protobuf:"varint,8,opt,name=query_type,json=queryType,proto3,enum=gsspb.QueryType" json:"query_type" xml:"query_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_gss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_gss_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStatus) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerStatus) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *ServerStatus) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *ServerStatus) GetNumPlayers() int32 {
	if x != nil {
		return x.NumPlayers
	}
	return 0
}

func (x *ServerStatus) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ServerStatus) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_UNKNOWN
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name" xml:"name"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id" xml:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_gss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_gss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_gss_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_gss_proto protoreflect.FileDescriptor

const file_gss_proto_rawDesc = "" +
	"\n" +
	"\tgss.proto\x12\x05gsspb\"\x81\x02\n" +
	"\fServerStatus\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bmap_name\x18\x04 \x01(\tR\amapName\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vnum_players\x18\x06 \x01(\x05R\n" +
	"numPlayers\x12'\n" +
	"\aplayers\x18\a \x03(\v2\r.gsspb.PlayerR\aplayers\x12/\n" +
	"\n" +
	"query_type\x18\b \x01(\x0e2\x10.gsspb.QueryTypeR\tqueryType\",\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id*?\n" +
	"\tQueryType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tMINECRAFT\x10\x01\x12\t\n" +
	"\x05GAMEQ\x10\x02\x12\v\n" +
	"\aGAMEDIG\x10\x03B\tZ\a./gsspbb\x06proto3"

var (
	file_gss_proto_rawDescOnce sync.Once
	file_gss_proto_rawDescData []byte
)

func file_gss_proto_rawDescGZIP() []byte {
	file_gss_proto_rawDescOnce.Do(func() {
		file_gss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gss_proto_rawDesc), len(file_gss_proto_rawDesc)))
	})
	return file_gss_proto_rawDescData
}

var file_gss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gss_proto_goTypes = []any{
	(QueryType)(0),       // 0: gsspb.QueryType
	(*ServerStatus)(nil), // 1: gsspb.ServerStatus
	(*Player)(nil),       // 2: gsspb.Player
}
var file_gss_proto_depIdxs = []int32{
	2, // 0: gsspb.ServerStatus.players:type_name -> gsspb.Player
	0, // 1: gsspb.ServerStatus.query_type:type_name -> gsspb.QueryType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gss_proto_init() }
func file_gss_proto_init() {
	if File_gss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gss_proto_rawDesc), len(file_gss_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gss_proto_goTypes,
		DependencyIndexes: file_gss_proto_depIdxs,
		EnumInfos:         file_gss_proto_enumTypes,
		MessageInfos:      file_gss_proto_msgTypes,
	}.Build()
	File_gss_proto = out.File
	file_gss_proto_goTypes = nil
	file_gss_proto_depIdxs = nil
}
